import SEO from '../components/SEO'
import './Privacy.css'

export default function Terms() {
  return (
    <>
      <SEO 
        title="Lingo Terms of Service"
        description="Terms of service for Lingo. Learn about your rights and responsibilities when using our AI translation service."
      />
      <div className="legal-page">
      <div className="container">
        <h1>Terms of Service</h1>
        <p className="last-updated">Last Updated: August 24, 2026</p>

        <div className="legal-content">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>By using Lingo, you agree to these Terms of Service. If you do not agree to these terms, please do not use the service.</p>
          </section>

          <section>
            <h2>2. Service Description</h2>
            <p>Lingo is a browser extension that provides in-place text translation services. The service translates text you are currently writing in web forms and content-editable areas.</p>
          </section>

          <section>
            <h2>3. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul>
              <li>Provide accurate information when activating licenses</li>
              <li>Not use Lingo for illegal purposes</li>
              <li>Not attempt to circumvent usage limits or licensing restrictions</li>
              <li>Not reverse-engineer or attempt to extract API keys from the extension</li>
              <li>Comply with all applicable laws and regulations</li>
            </ul>
          </section>

          <section>
            <h2>4. Accounts</h2>
            <p>You may be required to create an account to use certain features of Lingo. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
          </section>

          <section>
            <h2>5. Acceptable Use</h2>
            <p>You may not use Lingo to:</p>
            <ul>
              <li>Translate illegal, harmful, or offensive content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the rights of others</li>
              <li>Distribute malware or harmful code</li>
              <li>Attempt to gain unauthorized access to our systems</li>
            </ul>
          </section>

          <section>
            <h2>6. Subscription and Billing</h2>
            <h3>Free Tier</h3>
            <p>The free tier is available at no cost and includes 2 hours of translation per day with automatic refills.</p>
            
            <h3>Lingo Pro</h3>
            <p>Lingo Pro is available at $1.99/month after a first month free trial. Annual billing is available at $19.99/year.</p>
          </section>

          <section>
            <h2>7. Payment Processing</h2>
            <p>Payments are processed through Lemon Squeezy. Subscription fees are charged monthly or annually depending on your chosen plan. First month free applies to new Pro subscriptions only.</p>
          </section>

          <section>
            <h2>8. Trials</h2>
            <p>New Pro subscriptions include a first month free trial. You can cancel anytime before the trial ends with no charge.</p>
          </section>

          <section>
            <h2>9. Cancellation</h2>
            <p>You can cancel your Pro subscription at any time. Cancellation takes effect at the end of the current billing period. You retain Pro access until the end of the paid period.</p>
          </section>

          <section>
            <h2>10. Refunds</h2>
            <p>Refunds are handled on a case-by-case basis. Contact support for refund requests. First month free trial users are not charged.</p>
            <p><strong>Legal Review Required:</strong> Refund policies may vary by jurisdiction and require legal review.</p>
          </section>

          <section>
            <h2>11. Intellectual Property</h2>
            <p>Lingo extension and backend code are proprietary. You retain ownership of text you translate. We do not claim ownership of your content.</p>
          </section>

          <section>
            <h2>12. AI-Generated Content</h2>
            <p>Translations are generated by AI models. We do not guarantee accuracy or completeness of translations. You are responsible for reviewing translated content before use.</p>
          </section>

          <section>
            <h2>13. Third-Party Services</h2>
            <p>Lingo uses third-party services including Groq (AI models) and Lemon Squeezy (payment processing). Your use of these services is subject to their terms and conditions.</p>
          </section>

          <section>
            <h2>14. Service Availability</h2>
            <p>We strive to maintain high availability but do not guarantee 100% uptime. We may temporarily suspend the service for maintenance or updates. We are not liable for translation errors or inaccuracies.</p>
          </section>

          <section>
            <h2>15. Limitation of Liability</h2>
            <p>Lingo is provided "as is" without warranties of any kind. We are not liable for damages arising from use of the service.</p>
            <p><strong>Legal Review Required:</strong> Limitation of liability provisions require legal review and may vary by jurisdiction.</p>
          </section>

          <section>
            <h2>16. Changes to Service</h2>
            <p>We may modify the service, pricing, or these terms at any time. Continued use of the service constitutes acceptance of modified terms.</p>
          </section>

          <section>
            <h2>17. Termination</h2>
            <p>We reserve the right to terminate or suspend your account for violation of these terms or for any reason at our discretion.</p>
          </section>

          <section>
            <h2>18. Governing Law</h2>
            <p>These terms are governed by the laws of the jurisdiction where the service provider is registered.</p>
            <p><strong>Legal Review Required:</strong> Governing law provisions require legal review based on actual business location and target markets.</p>
          </section>

          <section>
            <h2>19. Contact</h2>
            <p>If you have questions about these terms, please contact us at:</p>
            <p><a href="/contact">Contact Page</a></p>
          </section>
        </div>
      </div>
    </div>
    </>
  )
}
